### ISSUE TITLE
Compilation error when hdk dependency is set to "develop" (Cargo.toml)

### ISSUE THREAD

**Issue by rzylber** [holochain/app-spec-rust#46]
Running `hc package --output dist/app-spec-rust.hcpkg --strip-meta`, 
I have the following error: 
`expected struct 'hdk::holochain_core_types::json::JsonString', found enum 'serde_json::Value' - expected 'hdk::holochain_core_types::json::JsonString' because of return type.`

See:
![screenshot from 2018-11-08 14-06-04](https://user-images.githubusercontent.com/3323843/48211241-3cba2d80-e360-11e8-94cf-0875fa1b7607.png)

But, if I change the lines related to hdk dependency, from **develop branch to master branch**, on these files: `app-spec-rust/zomes/blog/code/Cargo.toml` and `app-spec-rust/zomes/blog/code/Cargo.toml`,  the compilation works fine.

Is it a working in progress update, related to serde_json replacement by JsonString?
I don't know if it is an important issue, but if it could be solved it were great for the experience of newcomers, like me :-).

**Comment by Connoropolous** [comment]
Hi there... yes, it's a work-in-progress update that's being made, over in #45 

Sorry you bumped into it, it will be resolved soon

**Comment by rzylber** [comment]
No problem... ;-) Thank you very much!
